# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Test with Maven
      run: mvn test & echo -e "\nBuild Maven passed\nTest Maven passed\nJacoco Report" >> output/realization/realization.txt
    
    - name: test Echo1
        run: |
            echo -e "test1" >> test1.txt
            echo -e "test2" >> test2.txt
            echo -e "test3" >> test3.txt
    - name: Ls
      run:
        ls -la *
    - name: Realization
      run: echo -e "images Archivate!-!output/images/basic.svg;output/images/fig1.svg;output/images/fig2.gv;output/images/fig2.todo;output/images/fig3.svg;output/images/fig3.todo;output/images/Pattern4CI_Valid_REA.svg;output/images/Pattern4CI_NotValid_REA.svg;output/images/Pattern4CI_NotValid.todo;output/images/Pattern4CI_Valid.svg;output/images/Pattern4CI_Valid.todo;output/images/test_NC.svg;output/images/test_NC.todo!ref!images\nJacoco report Archivate!ref!jacoco\ncode Archivate!ref!generatedCode\nValid Continuous Integration!ref!GeneratedJD" >> output/realization/realization.txt
    - name: cat Realization
      run: cat output/realization/realization.txt
    - name: JD&TODO generation 
      run: mvn exec:java -Dexec.mainClass="JDCompiler" -Dexec.args="examples/Pattern4CI.jd -o output/GeneratedJD/Pattern4CI -svg -td output/realization/realization.txt -rea"
    - name: Archive JD&TODO
      uses: actions/upload-artifact@v2
      with: 
        name: GeneratedJD
        path: output/GeneratedJD
    - name: Archive realization
      uses: actions/upload-artifact@v2
      with: 
        name: GeneratedJD
        path: output/realization
    - name: Archive images
      uses: actions/upload-artifact@v2
      with: 
        name: images
        path: output/images
    - name: Archive Jacoco report
      uses: actions/upload-artifact@v2
      with: 
        name: jacoco
        path: target/site/jacoco
    - name: Archive generated codes
      uses: actions/upload-artifact@v2
      with: 
        name: generatedCode
        path: src/main/java/models
    
